---
title: "Spatial Ecology Final"
author: "Kari Norman"
date: "11/17/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#dyn.load('/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/server/libjvm.dylib')
library(rJava)
library(tidyverse)
library(raster)
library(dismo)
library(rgdal)
library(aws.s3)
```

```{r}
read_csv("data-private/bbs_full_2005_2015.csv") %>%
  dplyr::select(species, lat, long) %>%
  unique() -> bbs

wclim <- brick("data-private/wclim_study.area.tif", package = "raster")
```


```{r}
grid_sample <- function(data) {
  longrid <- seq(-160,-50, 0.2)
  latgrid <- seq(20, 70, 0.2)
  
  subs = c()
  for (i in 1:(length(longrid) - 1)) {
    for (j in 1:(length(latgrid) - 1)) {
      gridsq = subset(
        data,
        lat > latgrid[j] &
          lat < latgrid[j + 1] &
          long > longrid[i] & 
          long < longrid[i + 1]
      )
      if (dim(gridsq)[1] > 0) {
        subs = rbind(subs, gridsq[sample(1:dim(gridsq)[1], 1), ])
      }
    }
  }
  return(subs)
}


```

```{r}
#Plot points that result in NA's
coords <-  unique(bbs[c("long", "lat")])
coords_sp <- sp::SpatialPoints(coords, proj4string=CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"))
y <- raster::extract(wclim, coords_sp)
y <- as.data.frame(y)

y_na <- as.data.frame(which(is.na(y), arr.ind=TRUE))
na_rows <- unique(y_na$row)
bbs_na_coords <- as.data.frame(coords[na_rows,])

bio1 <- wclim[[1]]
heatScheme <- colorRampPalette(c("lightsteelblue", "goldenrod", "darkred"), bias=1, space="rgb", interpolate="linear")
plot(bio1, col = heatScheme(100), xlab="longitude", ylab="latitude", main = "Occurrence Data") 
points(bbs_na_coords, pch=20, col="blue", bg="blue")
```

```{r}
#Exclude locations with NA values before fitting sdm's
bbs_na_coords$EXTRACOL <- 1

bbs_merge <- merge(bbs, bbs_na_coords, by = c("lat", "long"), all=TRUE)
bbs_clean <- bbs_merge[is.na(bbs_merge$EXTRACOL),]
bbs_clean$EXTRACOL <- NULL
```

```{r}
#Generate maxent model for each species observed
species_id <- unique(bbs_clean$species)

bbs_samp <- list()
species_dist <- list()
for (i in 1:length(species_id)){
  species_data <- subset(bbs_clean, species == species_id[i])
  bbs_samp[[i]] <- grid_sample(species_data)
  species_dist[[i]] <- maxent(wclim, as.data.frame(cbind(bbs_samp[[i]]$long, bbs_samp[[i]]$lat)))
}

bbs_samp_big <- do.call(rbind, bbs_samp)
```

```{r}
#Get a count of the number of samples for each species
site_count <- list()
for (i in 1:length(species_id)){
  species_data <- subset(bbs_clean, species == species_id[i])
  if (dim(species_data[1]) > 25){
    site_count[[i]] <- dim(species_data)[1]
  }
}
site_count <- as.data.frame(site_count)
```

```{r}
#test predict function
test_occ <- subset(bbs_clean, species == species_id[3])
test_occ <- grid_sample(test_occ)
test_maxent <- maxent(wclim, as.data.frame(cbind(test_occ$long, test_occ$lat)))

test <- dismo::predict(test_maxent, wclim)
```

```{r}
# #test stacking loop
# species_stack <- stack()
# for(i in 1:length(species_dist)){
#   pred <- predict(species_dist[[i]], wclim)
#   species_stack <- stack(species_stack, pred)
# }
```

```{r}
#Full Humming bird analysis, fit model and predict
hum_id <- c(4270,4280,4290,4300,4310,4320,4330,4340,4360)

hum_samp <- list()
hum_dist <- list()
hum_stack <- stack()
for (i in 1:4){
  print(i)
  species_data <- subset(bbs_clean, species == hum_id[i])
  bbs_samp[[i]] <- grid_sample(species_data)
  species_dist[[i]] <- maxent(wclim, as.data.frame(cbind(bbs_samp[[i]]$long, bbs_samp[[i]]$lat)))
  pred <- predict(species_dist[[i]], wclim)
  hum_stack <- stack(hum_stack, pred)
}

hum_stack1 <- hum_stack
names(hum_stack1) <- c(4270,4280,4290,4300)

#write to tif
for (i in 1:length(names(hum_stack1))){
  file_name <- paste("data-private/hum_sdm", names(hum_stack1)[i], ".csv", sep="")
  writeRaster(hum_stack1[[i]],
                file_name,
                format = "GTiff",
                overwrite=TRUE)
}
```

```{r}
hum_samp <- list()
hum_dist <- list()
hum_stack <- stack()
for (i in 5:9){
  print(i)
  species_data <- subset(bbs_clean, species == hum_id[i])
  bbs_samp[[i]] <- grid_sample(species_data)
  species_dist[[i]] <- maxent(wclim, as.data.frame(cbind(bbs_samp[[i]]$long, bbs_samp[[i]]$lat)))
  pred <- predict(species_dist[[i]], wclim)
  hum_stack <- stack(hum_stack, pred)
}

hum_stack2 <- hum_stack
names(hum_stack2) <- c(4320,4330,4340,4360,4310)

#write to tif
for (i in 1:length(names(hum_stack2))){
  file_name <- paste("data-private/hum_sdm", names(hum_stack2)[i], ".csv", sep="")
  writeRaster(hum_stack2[[i]],
                file_name,
                format = "GTiff",
                overwrite=TRUE)
}
```

```{r}
#Merge Humming bird data
X4270 <- raster("data-private/hum_sdmX4270.tif")
X4280 <- raster("data-private/hum_sdmX4280.tif")
X4290 <- raster("data-private/hum_sdmX4290.tif")
X4300 <- raster("data-private/hum_sdmX4300.tif")

full_hum_stack <- stack(X4270, X4280, X4290, X4300, hum_stack2)
```

```{r}
#Plot example SDM with points
maxent1 <- predict(species_dist[[1]], wclim)
species_data <- subset(bbs_clean, species == species_id[1])

plot(maxent1, xlab="longitude", ylab="latitude", main = "Occurrence Data") 
points(as.data.frame(cbind(species_data$long, species_data$lat)), pch=20, col="blue", bg="blue")
```

```{r}
#get site lat longs, extract raster values
coords_clean <-  unique(bbs_clean[c("long", "lat")])
coords_clean_sp <- sp::SpatialPoints(coords_clean, proj4string=CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"))
y <- raster::extract(full_hum_stack, coords_clean_sp)
y <- cbind(coords_clean, as.data.frame(y))

y$richness <- apply(y[,c(-1,-2)], 1, function(x) sum(x >= 0.05))

as_tibble(y) %>%
  dplyr::select(long, lat, richness) %>%
  filter(richness > 0) -> richness_df

write.csv(richness_df, "data-private/hummingbird_SDM_richness.csv")
```
